package de.monokel.frontend.provider;

import java.util.HashMap;

import retrofit2.Call;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.POST;

/**
 * Interface for Retrofit which provides operations for client-server-communication.
 *
 * @author Philipp Alessandrini
 * @version 2020-10-17
 */
public interface RetrofitService {
    /**
     * GET-request to get a key which is generated by the server.
     *
     * @return a unique key
     */
    @GET("/request_key")
    Call<RequestedObject> requestKey();

    /**
     * POST-request to tell the server that this user is infected.
     *
     * @param keyMap unique key which is sent by the infected user
     */
    @POST("/report_infection")
    Call<Void> reportInfection(@Body HashMap<String, String> keyMap);
}